### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float64'

### ISSUE THREAD

**Issue by cstork** [dbt-labs/homebrew-dbt#19]
After successful `brew install dbt@0.20.0-rc2` invoking `dbt --version` produces:
```
Traceback (most recent call last):
  File "/usr/local/bin/dbt", line 33, in <module>
    sys.exit(load_entry_point('dbt-core==0.20.0rc2', 'console_scripts', 'dbt')())
  File "/usr/local/bin/dbt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 13, in <module>
    import dbt.task.run as run_task
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/task/run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/task/compile.py", line 2, in <module>
    from .runnable import GraphRunnableTask
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 16, in <module>
    from dbt.task.base import ConfiguredTask
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/task/base.py", line 22, in <module>
    from dbt.adapters.factory import register_adapter
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/adapters/factory.py", line 15, in <module>
    from dbt.adapters.protocol import (
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/adapters/protocol.py", line 21, in <module>
    from dbt.graph import Graph
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/graph/__init__.py", line 1, in <module>
    from .selector_spec import (  # noqa: F401
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/graph/selector_spec.py", line 9, in <module>
    from .graph import UniqueId
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/dbt/graph/graph.py", line 4, in <module>
    import networkx as nx  # type: ignore
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/networkx/__init__.py", line 64, in <module>
    import networkx.readwrite
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/networkx/readwrite/graphml.py", line 344, in <module>
    class GraphML:
  File "/usr/local/Cellar/dbt@0.20.0-rc2/0.20.0rc2_1/libexec/lib/python3.8/site-packages/networkx/readwrite/graphml.py", line 374, in GraphML
    (np.float64, "float"),
AttributeError: module 'numpy' has no attribute 'float64'
```
and `python38 -mpip install numpy` fixes it.  Maybe add the dependency?

**Comment by jtcohen6** [comment]
It looks like networkx v2.5 ([we're installing 2.5.1](https://github.com/dbt-labs/homebrew-dbt/blob/5073a65bec18ee0cfb3bcf8a33d635ccde431433/Formula/dbt%400.20.0-rc2.rb#L251)) includes `numpy` [as an extra](https://github.com/networkx/networkx/blob/36383ccc94a2e2d50893e13bb2a3ec96e5f6518f/setup.py#L127-L139), whereas the next minor version (v2.6) will be moving it into a default requirement: https://github.com/networkx/networkx/pull/4190

The error occurs just when trying to `import networkx as nx`, not from any method call in particular. During its `__init__`, `networkx` [sees if numpy is available](https://github.com/networkx/networkx/blob/36383ccc94a2e2d50893e13bb2a3ec96e5f6518f/networkx/readwrite/graphml.py#L366-L390): if so, use its types; if not, pass.

So my guess here is that you may have had a much older version of `numpy` installed, such that `networkx` was able to import it, but one which does not support the methods it was calling (i.e. `np.float64`).

**Comment by cstork** [comment]
Actually, I didn't have numpy installed at all in may Python 3.8 install.
